[package]
name = "is-lab4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libpcp = "0.7.0"
intervallum = "^1.0.0"
gcollections = "^1.0.0"
